version: '3.8'

services:
  # If have Postgres locally, uncomment and fill in env vars, if not, will use local sqlite database.
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=${}
  #     - POSTGRES_USER=${}
  #     - POSTGRES_PASSWORD=${}
  app:
    container_name: quantumapp
    build:
        context: .
        dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app/
      - db_data:/db.sqlite3
    command: python3 manage.py runserver 0.0.0.0:8000
    # command to run with gunicorn as web server
    # command: gunicorn quantumapp.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000

volumes:
  db_data:
  quantumapp:
