# Generated by Django 3.0.6 on 2020-05-19 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'credit',
                'verbose_name_plural': 'credits',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin_country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('timestamp', models.DateField()),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parkLocation', models.CharField(max_length=50)),
                ('parkCountry', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'park',
                'verbose_name_plural': 'parks',
            },
        ),
        migrations.CreateModel(
            name='RollerCoaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_height', models.CharField(max_length=50)),
                ('max_speed', models.CharField(max_length=50)),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumapi.Manufacturer')),
                ('park_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumapi.Park')),
            ],
            options={
                'verbose_name': 'rollerCoaster',
                'verbose_name_plural': 'rollerCoasters',
            },
        ),
        migrations.CreateModel(
            name='Tracktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tracktype',
                'verbose_name_plural': 'tracktypes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('picURL', models.ImageField(upload_to='')),
                ('roller_coaster_credits', models.ManyToManyField(through='quantumapi.Credit', to='quantumapi.RollerCoaster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userProfile',
                'verbose_name_plural': 'userProfiles',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('user.date_joined'), nulls_last=True),),
            },
        ),
        migrations.AddField(
            model_name='rollercoaster',
            name='tracktype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumapi.Tracktype'),
        ),
        migrations.AddField(
            model_name='rollercoaster',
            name='userProfile_credit_id',
            field=models.ManyToManyField(through='quantumapi.Credit', to='quantumapi.UserProfile'),
        ),
        migrations.AddField(
            model_name='credit',
            name='rollerCoaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumapi.RollerCoaster'),
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumapi.UserProfile'),
        ),
    ]
