# Generated by Django 3.0.7 on 2020-07-10 23:16

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name=django.forms.widgets.ClearableFileInput),
        ),
    ]
