# Generated by Django 3.0.6 on 2020-05-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userprofile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authuser', to='quantumapi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, unique=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
