# Generated by Django 3.0.7 on 2020-11-24 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContributorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, max_length=300, null=True)),
                ('date_submitted', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blogcontributorapplication',
                'verbose_name_plural': 'blogcontributorapplications',
            },
        ),
    ]
