# Generated by Django 3.0.7 on 2020-07-09 21:01

from django.db import migrations, models
import django.forms.widgets
import quantumapi.models.images


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_auto_20200709_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quantumapi.models.images.scramble_uploaded_filename, verbose_name=django.forms.widgets.ClearableFileInput),
        ),
    ]
