# Generated by Django 3.0.6 on 2020-05-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_messages_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rollercoaster',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='rollercoaster',
            old_name='park_id',
            new_name='park',
        ),
        migrations.RenameField(
            model_name='rollercoaster',
            old_name='tracktype_id',
            new_name='tracktype',
        ),
    ]
