# Generated by Django 3.0.6 on 2020-06-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_auto_20200530_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='origin_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rollercoaster',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='rollercoaster',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Park'),
        ),
        migrations.AlterField(
            model_name='rollercoaster',
            name='tracktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Tracktype'),
        ),
        migrations.AlterField(
            model_name='tracktype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
