# Generated by Django 3.0.7 on 2020-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_auto_20200728_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ('name',), 'verbose_name': 'park', 'verbose_name_plural': 'parks'},
        ),
    ]
