# Generated by Django 3.0.7 on 2020-11-19 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0002_auth0data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth0data',
            options={'ordering': ('user',), 'verbose_name': 'auth0data', 'verbose_name_plural': 'auth0data'},
        ),
        migrations.AlterField(
            model_name='auth0data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
