# Generated by Django 3.0.6 on 2020-05-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0003_auto_20200519_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='userProfile',
        ),
    ]
