# Generated by Django 3.0.7 on 2020-11-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0003_auto_20201119_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth0data',
            name='user_sub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_token', models.CharField(blank=True, max_length=100, null=True)),
                ('django_session', models.CharField(blank=True, max_length=200, null=True)),
                ('auth0data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantumapi.Auth0Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
                'ordering': ('user',),
            },
        ),
    ]
