# Generated by Django 3.0.7 on 2020-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0004_auto_20201125_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
