# Generated by Django 3.0.7 on 2020-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0004_auto_20201127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='django_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
