# Generated by Django 3.0.6 on 2020-05-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0004_auto_20200519_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='roller_coaster_credits',
            new_name='rollerCoaster_credits',
        ),
    ]
