# Generated by Django 3.0.6 on 2020-05-19 23:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0005_auto_20200519_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('user.date_joined'), nulls_last=True),), 'verbose_name': 'credit', 'verbose_name_plural': 'credits'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',), 'verbose_name': 'manufacturer', 'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('timestamp',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ('parkCountry',), 'verbose_name': 'park', 'verbose_name_plural': 'parks'},
        ),
        migrations.AlterModelOptions(
            name='rollercoaster',
            options={'ordering': ('manufacturer',), 'verbose_name': 'rollerCoaster', 'verbose_name_plural': 'rollerCoasters'},
        ),
        migrations.AlterModelOptions(
            name='tracktype',
            options={'ordering': ('name',), 'verbose_name': 'tracktype', 'verbose_name_plural': 'tracktypes'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='userProfile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rollercoaster',
            old_name='userProfile_credit_id',
            new_name='user_credit_id',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='company_website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
