# Generated by Django 3.0.7 on 2020-07-08 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0006_auto_20200708_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name=django.forms.widgets.ClearableFileInput)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picUrl',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantumapi.Image'),
        ),
    ]
