# Generated by Django 3.0.6 on 2020-05-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0006_auto_20200519_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'userProfile', 'verbose_name_plural': 'userProfiles'},
        ),
    ]
