# Generated by Django 3.0.5 on 2020-05-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0007_auto_20200519_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollercoaster',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='rollercoaster',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Park'),
        ),
        migrations.AlterField(
            model_name='rollercoaster',
            name='tracktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollercoasters', to='quantumapi.Tracktype'),
        ),
    ]
