# Generated by Django 3.0.6 on 2020-05-20 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0008_auto_20200520_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'userprofile', 'verbose_name_plural': 'userprofiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='rollerCoaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='quantumapi.RollerCoaster'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='quantumapi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
