# Generated by Django 3.0.7 on 2020-11-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0008_auto_20201128_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='transactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
