# Generated by Django 3.0.6 on 2020-05-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0009_auto_20200520_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picURL',
            new_name='picUrl',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rollerCoaster_credits',
            field=models.ManyToManyField(blank=True, null=True, through='quantumapi.Credit', to='quantumapi.RollerCoaster'),
        ),
    ]
