# Generated by Django 3.0.7 on 2020-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0009_auto_20201128_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
