# Generated by Django 3.0.7 on 2020-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0010_auto_20201128_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='django_token',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
