# Generated by Django 3.0.7 on 2020-11-29 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0011_auto_20201128_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, unique=True, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('recent_attempts', models.CharField(blank=True, max_length=2, null=True)),
                ('total_logins', models.CharField(blank=True, default=0, max_length=6, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('host_computer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('app_code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loginhistory',
                'verbose_name_plural': 'loginhistories',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activitylog',
                'verbose_name_plural': 'activitylogs',
                'ordering': ('user',),
            },
        ),
    ]
