# Generated by Django 3.0.7 on 2020-11-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0013_auto_20201129_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='appcodename',
            new_name='app_codename',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='hostcomputername',
            new_name='host_computer_name',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='ipaddress',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='recentattempts',
            new_name='recent_attempts',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='totallogins',
            new_name='total_logins',
        ),
    ]
