# Generated by Django 3.0.7 on 2020-11-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0014_auto_20201129_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(blank=True, default=[], null=True),
        ),
    ]
