# Generated by Django 3.0.6 on 2020-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0015_auto_20200521_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
