# Generated by Django 3.0.6 on 2020-05-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0017_auto_20200522_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
