# Generated by Django 3.0.7 on 2020-12-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0017_auto_20201211_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
