# Generated by Django 3.0.7 on 2020-12-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0019_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='function',
            new_name='calling_function',
        ),
    ]
