# Generated by Django 3.0.6 on 2020-05-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0020_auto_20200523_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'credit', 'verbose_name_plural': 'credits'},
        ),
    ]
