# Generated by Django 3.0.7 on 2020-12-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0021_auto_20201220_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='stack',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
