# Generated by Django 3.0.7 on 2020-12-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0022_auto_20201220_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='data',
        ),
    ]
