# Generated by Django 3.0.7 on 2020-12-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0023_remove_errorlog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
