# Generated by Django 3.0.7 on 2020-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0024_auto_20201220_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
