# Generated by Django 3.0.7 on 2020-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0025_auto_20201222_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ('user',), 'verbose_name': 'login history', 'verbose_name_plural': 'login history'},
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='id_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
