# Generated by Django 3.0.7 on 2020-12-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0027_credential_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
