# Generated by Django 3.0.7 on 2021-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0032_auto_20210129_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='password'),
        ),
    ]
