# Generated by Django 3.0.7 on 2021-02-08 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0033_auto_20210203_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('management_api_user', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('management_api_token', models.TextField(blank=True, null=True)),
                ('rest_auth_token', models.TextField(blank=True, null=True)),
                ('recent_attempts', models.CharField(blank=True, max_length=2, null=True)),
                ('total_logins', models.CharField(blank=True, default=0, max_length=6, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('oauth_endpoint_scopes', models.TextField(blank=True, null=True)),
                ('openid_configuration', models.TextField(blank=True, null=True)),
                ('grants', models.TextField(blank=True, null=True)),
                ('client_grants', models.TextField(blank=True, null=True)),
                ('connections', models.TextField(blank=True, null=True)),
                ('user_logs', models.TextField(blank=True, null=True)),
                ('resource_servers', models.TextField(blank=True, null=True)),
                ('management_api_keys', models.TextField(blank=True, null=True)),
                ('device_credentials', models.TextField(blank=True, null=True)),
                ('rest_auth_session', models.TextField(blank=True, null=True)),
                ('auth0_user_session', models.TextField(blank=True, null=True)),
                ('connection', models.TextField(blank=True, null=True)),
                ('connection_id', models.TextField(blank=True, null=True)),
                ('location_info', models.TextField(blank=True, null=True)),
                ('last_login_ip', models.TextField(blank=True, null=True)),
                ('social_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('client_name', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app Login Data',
                'verbose_name_plural': 'app Login Data',
                'ordering': ('user',),
            },
        ),
    ]
