# Generated by Django 3.0.7 on 2021-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0035_auto_20210208_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applogindata',
            old_name='auth0_user_session',
            new_name='management_session_id',
        ),
        migrations.AddField(
            model_name='applogindata',
            name='management_session_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
