# Generated by Django 3.0.7 on 2021-02-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('quantumapi', '0036_auto_20210208_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogindata',
            name='social_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
