# Generated by Django 3.0.7 on 2021-02-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0038_applogindata_prompts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applogindata',
            options={'ordering': ('auth_user',), 'verbose_name': 'app Login Data', 'verbose_name_plural': 'app Login Data'},
        ),
        migrations.RenameField(
            model_name='applogindata',
            old_name='user',
            new_name='auth_user',
        ),
        migrations.RenameField(
            model_name='applogindata',
            old_name='social_user_id',
            new_name='social_user',
        ),
    ]
