# Generated by Django 3.0.7 on 2021-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0039_auto_20210208_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogindata',
            name='oauth_endpoint_scopes',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='applogindata',
            name='recent_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applogindata',
            name='total_logins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
