# Generated by Django 3.0.7 on 2021-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0040_auto_20210210_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
