# Generated by Django 3.0.7 on 2021-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0042_auto_20210224_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='applogindata',
            name='tenant_settings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
