# Generated by Django 3.0.7 on 2021-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0043_applogindata_tenant_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracktype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
