# Generated by Django 3.0.7 on 2021-02-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapi', '0044_auto_20210225_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['date'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='applogindata',
            options={'ordering': ['updated_at'], 'verbose_name': 'app Login Data', 'verbose_name_plural': 'app Login Data'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['date'], 'verbose_name': 'error log', 'verbose_name_plural': 'error logs'},
        ),
    ]
