# Generated by Django 3.0.7 on 2021-01-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=2)),
            ],
            options={
                'verbose_name': 'Status Code',
                'verbose_name_plural': 'Status Codes',
            },
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumforum.Friendships')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'unique_together': {('requester', 'addressee')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender_and_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumforum.Friendships')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantumforum.StatusCode')),
            ],
            options={
                'verbose_name': 'friend Request',
                'verbose_name_plural': 'friend Requests',
            },
        ),
    ]
