# Generated by Django 3.0.7 on 2021-04-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersfriends',
            options={'verbose_name': 'UserFriend', 'verbose_name_plural': 'UsersFriends'},
        ),
    ]
