# Generated by Django 3.0.7 on 2021-02-04 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quantumapi', '0033_auto_20210203_1838'),
        ('quantumforum', '0003_auto_20210129_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('crated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupMembersJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantumforum.GroupChat')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantumapi.UserProfile')),
            ],
            options={
                'verbose_name': 'Group Chat Join',
                'verbose_name_plural': 'Group Chats Join',
            },
        ),
        migrations.AddField(
            model_name='groupchat',
            name='group_members',
            field=models.ManyToManyField(through='quantumforum.GroupMembersJoin', to='quantumapi.UserProfile'),
        ),
    ]
