# Generated by Django 3.0.7 on 2021-02-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumforum', '0004_auto_20210204_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
