# Generated by Django 3.0.7 on 2021-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumforum', '0008_auto_20210218_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
